### PR TITLE
fixes #29 by using standard place titles with types inside the 'contents...

### LINKED ISSUE #29: Subordinate Places: Labels
Tom, let's also include the place type label in the list of subordinate places [e.g. ‘Amādīyā (region)] to avoid giving the illusion of missing data (for example the list for ‘Amādīyā (region) is only the districts [e.g. Dohuk (district)] but technically each of the settlements in the districts is also subordinate to the region.

Further thought, do we want to keep "subordinate" or do we want to say "contains", subordinate is more accurate while contains is more readily understandable.

Thomas C. please feel free to weigh in.

### PR DESCRIPTION
**Pull request by paregorios**
...' div and uses the word 'Contains' for the list heading

### CODE REVIEW

**Comment by davidamichelson** [comment]
Before we merge this, do we want the Romanized and Syriac Headword to both display in the list of contains (as Tom currently has it doing)? I say yes, but this could get unwieldy.

Thomas what do you think?

**Comment by tacarlson** [comment]
So at present there will only very rarely be a Syriac name in the list of contained places (since all of that information is coming from Wilmshurst, who does not give Syriac forms).  Having the Syriac appear in the list of contained places when it occurs might be cool, but having the placeholder "[Syriac Not Available]" seems unnecessary and awkward to me, and at present that will be the vast majority of the contained places.

But stylistically, I would prefer to exclude the placeholder "[Syriac Not Available]" from the page heading as well, although I appreciate it in the browse lists.  But there will always be places (even important places, such as Dura-Europos) for which we have no Syriac form.  So I think we should discuss under what circumstances a place-holder should appear before we get into a tweaking war. =-)

**Comment by paregorios** [comment]
I'm cool with all that, and have a couple of suggestions on how to proceed. Let's go ahead and merge and publish this change and then have the discussion about labeling (opening a new ticket for that thread). Then we can make changes incrementally. The rationale for going ahead and pushing what we have now is that my implementation here has pulled much more of the titling and display of placenames into the single, standard template. We can more easily opt out of the rich display in some contexts in future by parameterizing that template. This will be a more sane development path. OK?

**Comment by davidamichelson** [comment]
Sounds great.

**Pull request merged**
